/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'name' : string,
  'section' : BookSection,
  'chapters' : bigint,
}
export type BookSection = { 'newTestament' : null } |
  { 'psalmsAndProphets' : null } |
  { 'oldTestament' : null };
export interface ProgressNote {
  'content' : string,
  'author' : Principal,
  'taskId' : bigint,
  'timestamp' : Time,
}
export interface Task {
  'status' : TaskStatus,
  'book' : Book,
  'type' : TaskType,
  'chapter' : bigint,
}
export interface TaskAssignment { 'task' : Task, 'notes' : Array<ProgressNote> }
export interface TaskInput {
  'bookName' : string,
  'projectType' : BookSection,
  'type' : TaskType,
  'chapter' : bigint,
}
export type TaskStatus = { 'videoReadyToRelease' : null } |
  { 'readyToRelease' : null } |
  { 'inProcessAudio' : null } |
  { 'pendingToRelease' : null } |
  { 'inProcessVideo' : null } |
  { 'audioReadyToRelease' : null };
export type TaskType = { 'editing' : null } |
  { 'audio' : null } |
  { 'video' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProgressNote' : ActorMethod<[bigint, string], ProgressNote>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTaskToUser' : ActorMethod<[Principal, TaskInput], undefined>,
  'createTask' : ActorMethod<[TaskInput], Task>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTasksByStatus' : ActorMethod<[], Array<[TaskStatus, Array<Task>]>>,
  'getAllTasksByType' : ActorMethod<[TaskType], Array<Task>>,
  'getAllTrackerTasksBySection' : ActorMethod<[], Array<TaskAssignment>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getBook' : ActorMethod<[string], [] | [Book]>,
  'getBooksBySection' : ActorMethod<[BookSection], Array<Book>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyTasks' : ActorMethod<[], Array<TaskAssignment>>,
  'getTaskProgressNotes' : ActorMethod<[bigint], Array<ProgressNote>>,
  'getTasksByBook' : ActorMethod<[string], Array<Task>>,
  'getTasksByStatus' : ActorMethod<[TaskStatus], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTask' : ActorMethod<[string, TaskInput], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];