/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ProgressNote = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'taskId' : IDL.Nat,
  'timestamp' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookSection = IDL.Variant({
  'newTestament' : IDL.Null,
  'psalmsAndProphets' : IDL.Null,
  'oldTestament' : IDL.Null,
});
export const TaskType = IDL.Variant({
  'editing' : IDL.Null,
  'audio' : IDL.Null,
  'video' : IDL.Null,
});
export const TaskInput = IDL.Record({
  'bookName' : IDL.Text,
  'projectType' : BookSection,
  'type' : TaskType,
  'chapter' : IDL.Nat,
});
export const TaskStatus = IDL.Variant({
  'videoReadyToRelease' : IDL.Null,
  'readyToRelease' : IDL.Null,
  'inProcessAudio' : IDL.Null,
  'pendingToRelease' : IDL.Null,
  'inProcessVideo' : IDL.Null,
  'audioReadyToRelease' : IDL.Null,
});
export const Book = IDL.Record({
  'name' : IDL.Text,
  'section' : BookSection,
  'chapters' : IDL.Nat,
});
export const Task = IDL.Record({
  'status' : TaskStatus,
  'book' : Book,
  'type' : TaskType,
  'chapter' : IDL.Nat,
});
export const TaskAssignment = IDL.Record({
  'task' : Task,
  'notes' : IDL.Vec(ProgressNote),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProgressNote' : IDL.Func([IDL.Nat, IDL.Text], [ProgressNote], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTaskToUser' : IDL.Func([IDL.Principal, TaskInput], [], []),
  'createTask' : IDL.Func([TaskInput], [Task], []),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTasksByStatus' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(TaskStatus, IDL.Vec(Task)))],
      ['query'],
    ),
  'getAllTasksByType' : IDL.Func([TaskType], [IDL.Vec(Task)], ['query']),
  'getAllTrackerTasksBySection' : IDL.Func(
      [],
      [IDL.Vec(TaskAssignment)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
  'getBooksBySection' : IDL.Func([BookSection], [IDL.Vec(Book)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyTasks' : IDL.Func([], [IDL.Vec(TaskAssignment)], ['query']),
  'getTaskProgressNotes' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProgressNote)],
      ['query'],
    ),
  'getTasksByBook' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTasksByStatus' : IDL.Func([TaskStatus], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTask' : IDL.Func([IDL.Text, TaskInput], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ProgressNote = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'taskId' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookSection = IDL.Variant({
    'newTestament' : IDL.Null,
    'psalmsAndProphets' : IDL.Null,
    'oldTestament' : IDL.Null,
  });
  const TaskType = IDL.Variant({
    'editing' : IDL.Null,
    'audio' : IDL.Null,
    'video' : IDL.Null,
  });
  const TaskInput = IDL.Record({
    'bookName' : IDL.Text,
    'projectType' : BookSection,
    'type' : TaskType,
    'chapter' : IDL.Nat,
  });
  const TaskStatus = IDL.Variant({
    'videoReadyToRelease' : IDL.Null,
    'readyToRelease' : IDL.Null,
    'inProcessAudio' : IDL.Null,
    'pendingToRelease' : IDL.Null,
    'inProcessVideo' : IDL.Null,
    'audioReadyToRelease' : IDL.Null,
  });
  const Book = IDL.Record({
    'name' : IDL.Text,
    'section' : BookSection,
    'chapters' : IDL.Nat,
  });
  const Task = IDL.Record({
    'status' : TaskStatus,
    'book' : Book,
    'type' : TaskType,
    'chapter' : IDL.Nat,
  });
  const TaskAssignment = IDL.Record({
    'task' : Task,
    'notes' : IDL.Vec(ProgressNote),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProgressNote' : IDL.Func([IDL.Nat, IDL.Text], [ProgressNote], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTaskToUser' : IDL.Func([IDL.Principal, TaskInput], [], []),
    'createTask' : IDL.Func([TaskInput], [Task], []),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTasksByStatus' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(TaskStatus, IDL.Vec(Task)))],
        ['query'],
      ),
    'getAllTasksByType' : IDL.Func([TaskType], [IDL.Vec(Task)], ['query']),
    'getAllTrackerTasksBySection' : IDL.Func(
        [],
        [IDL.Vec(TaskAssignment)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getBook' : IDL.Func([IDL.Text], [IDL.Opt(Book)], ['query']),
    'getBooksBySection' : IDL.Func([BookSection], [IDL.Vec(Book)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyTasks' : IDL.Func([], [IDL.Vec(TaskAssignment)], ['query']),
    'getTaskProgressNotes' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProgressNote)],
        ['query'],
      ),
    'getTasksByBook' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTasksByStatus' : IDL.Func([TaskStatus], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTask' : IDL.Func([IDL.Text, TaskInput], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };