/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TaskInput {
    bookName: string;
    projectType: BookSection;
    type: TaskType;
    chapter: bigint;
}
export interface TaskAssignment {
    task: Task;
    notes: Array<ProgressNote>;
}
export type Time = bigint;
export interface ProgressNote {
    content: string;
    author: Principal;
    taskId: bigint;
    timestamp: Time;
}
export interface Task {
    status: TaskStatus;
    book: Book;
    type: TaskType;
    chapter: bigint;
}
export interface Book {
    name: string;
    section: BookSection;
    chapters: bigint;
}
export interface UserProfile {
    name: string;
}
export enum BookSection {
    newTestament = "newTestament",
    psalmsAndProphets = "psalmsAndProphets",
    oldTestament = "oldTestament"
}
export enum TaskStatus {
    videoReadyToRelease = "videoReadyToRelease",
    readyToRelease = "readyToRelease",
    inProcessAudio = "inProcessAudio",
    pendingToRelease = "pendingToRelease",
    inProcessVideo = "inProcessVideo",
    audioReadyToRelease = "audioReadyToRelease"
}
export enum TaskType {
    editing = "editing",
    audio = "audio",
    video = "video"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProgressNote(taskId: bigint, content: string): Promise<ProgressNote>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignTaskToUser(user: Principal, input: TaskInput): Promise<void>;
    createTask(input: TaskInput): Promise<Task>;
    getAllBooks(): Promise<Array<Book>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllTasksByStatus(): Promise<Array<[TaskStatus, Array<Task>]>>;
    getAllTasksByType(taskType: TaskType): Promise<Array<Task>>;
    getAllTrackerTasksBySection(): Promise<Array<TaskAssignment>>;
    getAllUserProfiles(): Promise<Array<UserProfile>>;
    getBook(name: string): Promise<Book | null>;
    getBooksBySection(section: BookSection): Promise<Array<Book>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyTasks(): Promise<Array<TaskAssignment>>;
    getTaskProgressNotes(taskId: bigint): Promise<Array<ProgressNote>>;
    getTasksByBook(book: string): Promise<Array<Task>>;
    getTasksByStatus(taskStatus: TaskStatus): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateTask(bookName: string, update: TaskInput): Promise<void>;
    updateTaskStatus(id: bigint, status: TaskStatus): Promise<void>;
}
import type { Book as _Book, BookSection as _BookSection, ProgressNote as _ProgressNote, Task as _Task, TaskAssignment as _TaskAssignment, TaskInput as _TaskInput, TaskStatus as _TaskStatus, TaskType as _TaskType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProgressNote(arg0: bigint, arg1: string): Promise<ProgressNote> {
        if (this.processError) {
            try {
                const result = await this.actor.addProgressNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProgressNote(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignTaskToUser(arg0: Principal, arg1: TaskInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignTaskToUser(arg0, to_candid_TaskInput_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignTaskToUser(arg0, to_candid_TaskInput_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTask(arg0: TaskInput): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_TaskInput_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Task_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_TaskInput_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Task_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBooks(): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBooks();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBooks();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasksByStatus(): Promise<Array<[TaskStatus, Array<Task>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasksByStatus();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasksByStatus();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasksByType(arg0: TaskType): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasksByType(to_candid_TaskType_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasksByType(to_candid_TaskType_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTrackerTasksBySection(): Promise<Array<TaskAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTrackerTasksBySection();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTrackerTasksBySection();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getBook(arg0: string): Promise<Book | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBook(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBook(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooksBySection(arg0: BookSection): Promise<Array<Book>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooksBySection(to_candid_BookSection_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooksBySection(to_candid_BookSection_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTasks(): Promise<Array<TaskAssignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTasks();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTasks();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskProgressNotes(arg0: bigint): Promise<Array<ProgressNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskProgressNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskProgressNotes(arg0);
            return result;
        }
    }
    async getTasksByBook(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByBook(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByBook(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksByStatus(arg0: TaskStatus): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByStatus(to_candid_TaskStatus_n30(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByStatus(to_candid_TaskStatus_n30(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateTask(arg0: string, arg1: TaskInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, to_candid_TaskInput_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, to_candid_TaskInput_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskStatus(arg0: bigint, arg1: TaskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookSection_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookSection): BookSection {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Book_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Book): Book {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TaskAssignment_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskAssignment): TaskAssignment {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TaskType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskType): TaskType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Book]): Book | null {
    return value.length === 0 ? null : from_candid_Book_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TaskStatus;
    book: _Book;
    type: _TaskType;
    chapter: bigint;
}): {
    status: TaskStatus;
    book: Book;
    type: TaskType;
    chapter: bigint;
} {
    return {
        status: from_candid_TaskStatus_n11(_uploadFile, _downloadFile, value.status),
        book: from_candid_Book_n13(_uploadFile, _downloadFile, value.book),
        type: from_candid_TaskType_n17(_uploadFile, _downloadFile, value.type),
        chapter: value.chapter
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    section: _BookSection;
    chapters: bigint;
}): {
    name: string;
    section: BookSection;
    chapters: bigint;
} {
    return {
        name: value.name,
        section: from_candid_BookSection_n15(_uploadFile, _downloadFile, value.section),
        chapters: value.chapters
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    task: _Task;
    notes: Array<_ProgressNote>;
}): {
    task: Task;
    notes: Array<ProgressNote>;
} {
    return {
        task: from_candid_Task_n9(_uploadFile, _downloadFile, value.task),
        notes: value.notes
    };
}
function from_candid_tuple_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_TaskStatus, Array<_Task>]): [TaskStatus, Array<Task>] {
    return [
        from_candid_TaskStatus_n11(_uploadFile, _downloadFile, value[0]),
        from_candid_vec_n20(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    videoReadyToRelease: null;
} | {
    readyToRelease: null;
} | {
    inProcessAudio: null;
} | {
    pendingToRelease: null;
} | {
    inProcessVideo: null;
} | {
    audioReadyToRelease: null;
}): TaskStatus {
    return "videoReadyToRelease" in value ? TaskStatus.videoReadyToRelease : "readyToRelease" in value ? TaskStatus.readyToRelease : "inProcessAudio" in value ? TaskStatus.inProcessAudio : "pendingToRelease" in value ? TaskStatus.pendingToRelease : "inProcessVideo" in value ? TaskStatus.inProcessVideo : "audioReadyToRelease" in value ? TaskStatus.audioReadyToRelease : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newTestament: null;
} | {
    psalmsAndProphets: null;
} | {
    oldTestament: null;
}): BookSection {
    return "newTestament" in value ? BookSection.newTestament : "psalmsAndProphets" in value ? BookSection.psalmsAndProphets : "oldTestament" in value ? BookSection.oldTestament : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    editing: null;
} | {
    audio: null;
} | {
    video: null;
}): TaskType {
    return "editing" in value ? TaskType.editing : "audio" in value ? TaskType.audio : "video" in value ? TaskType.video : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Book>): Array<Book> {
    return value.map((x)=>from_candid_Book_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_TaskStatus, Array<_Task>]>): Array<[TaskStatus, Array<Task>]> {
    return value.map((x)=>from_candid_tuple_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskAssignment>): Array<TaskAssignment> {
    return value.map((x)=>from_candid_TaskAssignment_n24(_uploadFile, _downloadFile, x));
}
function to_candid_BookSection_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookSection): _BookSection {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TaskInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskInput): _TaskInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_TaskType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): _TaskType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bookName: string;
    projectType: BookSection;
    type: TaskType;
    chapter: bigint;
}): {
    bookName: string;
    projectType: _BookSection;
    type: _TaskType;
    chapter: bigint;
} {
    return {
        bookName: value.bookName,
        projectType: to_candid_BookSection_n5(_uploadFile, _downloadFile, value.projectType),
        type: to_candid_TaskType_n7(_uploadFile, _downloadFile, value.type),
        chapter: value.chapter
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    videoReadyToRelease: null;
} | {
    readyToRelease: null;
} | {
    inProcessAudio: null;
} | {
    pendingToRelease: null;
} | {
    inProcessVideo: null;
} | {
    audioReadyToRelease: null;
} {
    return value == TaskStatus.videoReadyToRelease ? {
        videoReadyToRelease: null
    } : value == TaskStatus.readyToRelease ? {
        readyToRelease: null
    } : value == TaskStatus.inProcessAudio ? {
        inProcessAudio: null
    } : value == TaskStatus.pendingToRelease ? {
        pendingToRelease: null
    } : value == TaskStatus.inProcessVideo ? {
        inProcessVideo: null
    } : value == TaskStatus.audioReadyToRelease ? {
        audioReadyToRelease: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookSection): {
    newTestament: null;
} | {
    psalmsAndProphets: null;
} | {
    oldTestament: null;
} {
    return value == BookSection.newTestament ? {
        newTestament: null
    } : value == BookSection.psalmsAndProphets ? {
        psalmsAndProphets: null
    } : value == BookSection.oldTestament ? {
        oldTestament: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskType): {
    editing: null;
} | {
    audio: null;
} | {
    video: null;
} {
    return value == TaskType.editing ? {
        editing: null
    } : value == TaskType.audio ? {
        audio: null
    } : value == TaskType.video ? {
        video: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
